name: common tester workflow

on:
  workflow_call:
    inputs:
      dbunit-version:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          show-download-progress: true

      - run: |
          mvn test -Ddbunit.version=${{ inputs.dbunit-version }}
